services:
  server:
    build:
      context: .
      target: final
    command:
      - up
      - --mode=dev
      - -C
      - http.service_url=https://autokitteh.lovelane.co.zw
    ports:
      - 9980:9980
      - 9982:9982
    labels:
      # Backend API (port 9980) on autokitteh.lovelane.co.zw
      - traefik.http.routers.ak-backend-web.rule=Host(`autokitteh.lovelane.co.zw`)
      - traefik.http.routers.ak-backend-web.entrypoints=web
      - traefik.http.routers.ak-backend-web.middlewares=redirect-to-https@file
      - traefik.http.routers.ak-backend-web.service=ak-backend

      - traefik.http.routers.ak-backend-secure.rule=Host(`autokitteh.lovelane.co.zw`)
      - traefik.http.routers.ak-backend-secure.entrypoints=websecure
      - traefik.http.routers.ak-backend-secure.tls.certresolver=letsencrypt
      - traefik.http.routers.ak-backend-secure.service=ak-backend

      - traefik.http.services.ak-backend.loadbalancer.server.port=9980

      # Frontend Admin UI (port 9982) on autokittehadmin.lovelane.co.zw
      - traefik.http.routers.ak-frontend-web.rule=Host(`autokittehadmin.lovelane.co.zw`)
      - traefik.http.routers.ak-frontend-web.entrypoints=web
      - traefik.http.routers.ak-frontend-web.middlewares=redirect-to-https@file
      - traefik.http.routers.ak-frontend-web.service=ak-frontend

      - traefik.http.routers.ak-frontend-secure.rule=Host(`autokittehadmin.lovelane.co.zw`)
      - traefik.http.routers.ak-frontend-secure.entrypoints=websecure
      - traefik.http.routers.ak-frontend-secure.tls.certresolver=letsencrypt
      - traefik.http.routers.ak-frontend-secure.service=ak-frontend

      - traefik.http.services.ak-frontend.loadbalancer.server.port=9982

      - traefik.docker.network=dokploy-network
      - traefik.enable=true
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
